### ISSUE TITLE
Arithmetic error

### ISSUE THREAD

**Issue by denis-yuen** [ICGC-TCGA-PanCancer/SeqWare-CGP-SomaticCore#31]
I had this issue on a host with 22G of memory with the 1.0.4 workflow
With the following settings :

        memHostMbAvailable=22000 
        memPindelPerThread=20000

I had the following error on launch:

        [SeqWare Pipeline] FATAL [2015/02/06 18:57:48] | Exception constructing data model, failing workflow 223
       java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       ... 
        Caused by: java.lang.ArithmeticException: / by zero
        at io.seqware.pancancer.CgpCnIndelSnvStrWorkflow.buildPairWorkflow(CgpCnIndelSnvStrWorkflow.java:542)
        at io.seqware.pancancer.CgpCnIndelSnvStrWorkflow.buildWorkflow(CgpCnIndelSnvStrWorkflow.java:385)

Fixed by reducing the memPindelPerThread value.

**Comment by keiranmraine** [comment]
This can happen when ``memHostMbAvailable`` - ``memWorkflowOverhead`` is less than the ``mem*PerThread`` value.

I'll add an informative runtime exception message and also patch the first element of the ``if`` block to be ``>=``.

https://github.com/ICGC-TCGA-PanCancer/SeqWare-CGP-SomaticCore/blob/develop/src/main/java/io/seqware/pancancer/CgpCnIndelSnvStrWorkflow.java#L1297-L1311

Likely message:

    memHostMbAvailable - memWorkflowOverhead = memoryAvail (values) is less than one of the mem*PerThread parameters in provided ini file.

**Comment by denis-yuen** [comment]
@keiranmraine  Thanks for the heads-up and warning message.
