### ISSUE TITLE
Bad parameter for gtdownload in 1.0.6

### ISSUE THREAD

**Issue by niall-byrne** [ICGC-TCGA-PanCancer/SeqWare-CGP-SomaticCore#41]
The following happened on my 1.0.6 install:

The shell script was populated with the following command:
```perl -I /home/seqware/provisioned-bundles/Workflow_Bundle_SangerPancancerCgpCnIndelSnvStr_1.0.6_SeqWare_1.1.0/Workflow_Bundle_SangerPancancerCgpCnIndelSnvStr/1.0.6/lib /home/seqware/provisioned-bundles/Workflow_Bundle_SangerPancancerCgpCnIndelSnvStr_1.0.6_SeqWare_1.1.0/Workflow_Bundle_SangerPancancerCgpCnIndelSnvStr/1.0.6/bin/gnos_download_file.pl   -k 60  --pem /mnt/home/seqware/gnos.pem  --url https://gtrepo-dkfz.annailabs.com//cghub/data/analysis/download/c9e1c0e7-e10f-41f1-83e4-f201cf01d40d  --file c9e1c0e7-e10f-41f1-83e4-f201cf01d40d/90228f6e766a87b3080a7d3a106d94b7.bam  --retries 3 --sleep-min 1 --timeout-min 20```

The perl script it was calling however, did not understand the ```-k 60``` parameter.
I was able to get the workflow run to finish correctly, but it was a bit unusual.

GeneTorrent gtdownload release 3.8.5 (SCM REV: git ref: 1b8e7685d6, build: 91)

**Comment by a8wright** [comment]
I am pretty sure this is because the -k parameter is no longer being used with the gtwrapper. If this is a necessary features we could put time into making a newer version of the wrapper. It would not take very long to add in.

**Comment by keiranmraine** [comment]
I've previously reported this to Brian/Solomon.  Any reason not using 1.0.7 it resolves a few edge cases?

**Comment by niall-byrne** [comment]
I think breaking the parameterization is a bad idea- backwards compatibility should probably be maintained.  How widely tested has 1.0.7 been?  1.0.6 has been a pretty good workhorse up to now.

**Comment by SolomonShorser-OICR** [comment]
Hi Keiran,
Is testing complete for 1.0.7? If so, I can close the release branch and 
make it the default version.

Thanks,
Solomon Shorser.

On 15-06-22 04:32 PM, Keiran Raine wrote:
>
> I've previously reported this to Brian/Solomon. Any reason not using 
> 1.0.7 it resolves a few edge cases?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ICGC-TCGA-PanCancer/SeqWare-CGP-SomaticCore/issues/41#issuecomment-114254433>.
>

*Solomon Shorser*
Software Developer

*Ontario Institute for Cancer Research*
MaRS Centre
661 University Avenue
Suite 510
Toronto, Ontario
Canada M5G 0A3

Email: Solomon.Shorser@gmail.com
Toll-free: 1-866-678-6427
Twitter: @OICR_news

www.oicr.on.ca <http://www.oicr.on.ca/>

This message and any attachments may contain confidential and/or 
privileged information for the sole use of the intended recipient. Any 
review or distribution by anyone other than the person for whom it was 
originally intended is strictly prohibited. If you have received this 
message in error, please contact the sender and delete all copies. 
Opinions, conclusions or other information contained in this message may 
not be that of the organization.

**Comment by keiranmraine** [comment]
Hi Solomon, there have been successfully completed runs (the first couple were unfortunately tagged as 1.0.6 in the ini file though).

Sorry I forgot to feed back when they finished the runs.

Keiran Raine
Principal Bioinformatician
Cancer Genome Project
Wellcome Trust Sanger Institute

kr2@sanger.ac.uk
Tel:+44 (0)1223 834244 Ext: 7703
Office: H104

On 22 Jun 2015, at 21:45, Solomon Shorser <notifications@github.com> wrote:

> Hi Keiran,
> Is testing complete for 1.0.7? If so, I can close the release branch and 
> make it the default version.
> 
> Thanks,
> Solomon Shorser.
> 
> On 15-06-22 04:32 PM, Keiran Raine wrote:
> >
> > I've previously reported this to Brian/Solomon. Any reason not using 
> > 1.0.7 it resolves a few edge cases?
> >
> > —
> > Reply to this email directly or view it on GitHub 
> > <https://github.com/ICGC-TCGA-PanCancer/SeqWare-CGP-SomaticCore/issues/41#issuecomment-114254433>.
> >
> 
> *Solomon Shorser*
> Software Developer
> 
> *Ontario Institute for Cancer Research*
> MaRS Centre
> 661 University Avenue
> Suite 510
> Toronto, Ontario
> Canada M5G 0A3
> 
> Email: Solomon.Shorser@gmail.com
> Toll-free: 1-866-678-6427
> Twitter: @OICR_news
> 
> www.oicr.on.ca <http://www.oicr.on.ca/>
> 
> This message and any attachments may contain confidential and/or 
> privileged information for the sole use of the intended recipient. Any 
> review or distribution by anyone other than the person for whom it was 
> originally intended is strictly prohibited. If you have received this 
> message in error, please contact the sender and delete all copies. 
> Opinions, conclusions or other information contained in this message may 
> not be that of the organization.
> 
> —
> Reply to this email directly or view it on GitHub.
> 




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by niall-byrne** [comment]
Hi all,

This is still causing problems for me in 1.0.7 installs.
The parameterization of the wrapper still seems to be incorrect:

                  .addArgument(" -k 60") 
                  .addArgument(" --pem "+ pemFile)
                  .addArgument(" --url " + gnosServer + "/cghub/data/analysis/download/" + analysisId)
                  .addArgument(" --file " + bamFile )
                  .addArgument(" --retries "+retries+" --sleep-min 1 --timeout-min " + timeoutMin) ;

We either need to add backwards compatibility to the wrapper, or change the workflow itself.
The way it builds right now, this won't run out of the box.  (ie. the wrapper will fail on parameterization)

I thought initially it may have been just my environment, but I'm seeing it on subsequent fresh installs, in multiple environments.

**Comment by keiranmraine** [comment]
I get warnings but it runs fine. It fails if the repo url has a trailing / but thats an issue with the ini file template population.

**Comment by niall-byrne** [comment]
I have seen in fail in at least 2 environments now.
In both cases I had to fix it by 'sed'ing out the -k as well as the entire --retries section.  In these cases it was hard failing, and I didn't have to change the urls themselves.  

Interestingly, the upload is parameterized differently, and seems to work fine.
We should compare notes on the ini files and see if it is and url problem or something else that's not populated correctly, but the work around I noted above is the only fix I've had success with.

**Comment by denis-yuen** [comment]
Our experience at ETRI and EBI with 1.0.7 matches Keiran's, we always get warnings but it still runs.
On Monday, we should exchange ini files, md5sum your bundles (and the uncompressed workflow), etc.

**Comment by keiranmraine** [comment]
My images in use are:

* pancancer/seqware_whitestar_pancancer:1.1.1
* seqware/seqware-distribution/1.1.0/seqware-distribution-1.1.0-full.jar
* oicr.workflow.bundles/released-bundles/Workflow_Bundle_SangerPancancerCgpCnIndelSnvStr_1.0.7_SeqWare_1.1.0.zip

```
# the output directory is a convention used in many workflows to specify a relative output path
output_dir=seqware-results
# the output_prefix is a convention used to specify the root of the absolute output path or an S3 bucket name
# you should pick a path that is available on all cluster nodes and can be written by your user
output_prefix=./
# cleanup true will remove just the input BAMs if not uploading and the full output directory if uploading
# false there will be no cleanup which is useful for debugging
cleanup=

# START NEW ITEMS

# these are just used for tracking
donor_id=PCSI_0337
project_code=PACA-CA
workflow_version=1.0.7
workflow_name=SangerPancancerCgpCnIndelSnvStr

# memory for upload to SFTP/S3
duckJobMem=16000

# tracking instance types
vm_instance_type=sanger
vm_instance_cores=32
vm_instance_mem_gb=250
vm_location_code=sanger

# cleanup
cleanupBams=

# archive tarball
saveUploadArchive=true
uploadArchivePath=./seqware-results/upload_archive/

# options for tarball to SFTP
SFTPUploadArchive=false
# can be overwrite or skip, see https://trac.cyberduck.io/wiki/help/en/howto/cli
SFTPUploadArchiveMode=overwrite
SFTPUploadArchiveUsername=...
SFTPUploadArchivePassword=...
SFTPUploadArchiveServer=...
SFTPUploadArchivePath=/upload/path/directory/

# options for tarball to S3
S3UploadArchive=false
S3UploadArchiveMode=overwrite
S3UploadArchiveBucketURL=s3://bucketname/uploads/
S3UploadArchiveKey=...
S3UploadArchiveSecretKey=...

# send the files not a tarball
SFTPUploadFiles=false
# can be overwrite or skip, see https://trac.cyberduck.io/wiki/help/en/howto/cli
SFTPUploadMode=overwrite
SFTPUploadUsername=...
SFTPUploadPassword=...
SFTPUploadServer=...
SFTPUploadPath=/upload/path/directory/

S3UploadFiles=false
S3UploadFileMode=...
S3UploadBucketURL=...
S3UploadKey=...
S3UploadSecretKey=...

# synapse upload
SynapseUpload=false
SynapseUploadSFTPUsername=...
SynapseUploadSFTPPassword=...
SynapseUploadUsername=...
SynapseUploadPassword=...
SynapseUploadURL=...
SynapseUploadParent=...

# if set, these trigger an upload of the input bam file to a GNOS repository
bamUploadServer=
bamUploadPemFile=
bamUploadStudyRefnameOverride=
bamUploadAnalysisCenterOverride=
bamUploadScriptJobMem=10000
bamUploadScriptJobSlots=1

# if set to true GNOS is still used for downloading metadata but the input bam file paths are assumed to be local file paths
# specifically tumourBams is a colon-delimited list of full file paths and controlBam is a full file path
localFileMode=
# if localFileMode is true then you need to give the path where the decider downloads all the XML
# this is the path that the VM/Docker/workflow sees (might be different from your path)
localXMLMetadataPath=

# another option for upload
skip-validate=

# when localFileMode=true, if set this causes the bam file paths to be modified so they are <localBamFilePathPrefix>/<analysis_id>/<bam_file>, also affects the bai path implicitly. This is done so you can continue working with the decider.
localBamFilePathPrefix=

# END NEW ITEMS

# basic setup
coresAddressable=32
memHostMbAvailable=250000
tabixSrvUri=http://cgp-1-1-15.internal.sanger.ac.uk:8081/
pemFile=/workflow/ICGC.pem
uploadPemFile=/workflow/ICGC.pem
seqware-output-lines-number=5000
gnosServer=https://gtrepo-bsc.annailabs.com/
## comment out upload server to block vcfUpload
uploadServer=https://gtrepo-bsc.annailabs.com

study-refname-override=icgc_pancancer_vcf
analysis-center-override=sanger
#center-override=
#ref-center-override=
upload-test=
upload-skip=

assembly=GRCh37
species=human
seqType=WGS
gender=L

# test data, will be overriden unless testMode=true
testMode=

# the donor information
tumourAliquotIds=e7603fc8-9b73-4c17-86f9-46ca1bceeb1d
tumourAnalysisIds=fb3216f5-4360-404c-81d5-cc2a157554cb
tumourBams=9226d18ca5ba89ecd08e6c882bafa9e0.bam
controlAnalysisId=8d2fa447-109a-482e-bda4-3193f00e60f7
controlBam=4a6e6bd4169a1543b386db990bb7311e.bam

refExclude=MT,GL%,hs37d5,NC_007605

...memory bits removed for brevity...
```

**Comment by niall-byrne** [comment]
I'm running an oldschool oozie/sge based instance, seqware version 1.1.0.
oicr.workflow.bundles/released-bundles/Workflow_Bundle_SangerPancancerCgpCnIndelSnvStr_1.0.7_SeqWare_1.1.0.zip

`# the output directory is a convention used in many workflows to specify a relative output path
output_dir=seqware-results
# the output_prefix is a convention used to specify the root of the absolute output path or an S3 bucket name
# you should pick a path that is available on all cluster nodes and can be written by your user
output_prefix=./
# cleanup true will remove just the input BAMs if not uploading and the full output directory if uploading
# false there will be no cleanup which is useful for debugging
cleanup=

# START NEW ITEMS

# these are just used for tracking
donor_id=EOPC-037
project_code=EOPC-DE
workflow_version=1.0.7
workflow_name=SangerPancancerCgpCnIndelSnvStr

# memory for upload to SFTP/S3
duckJobMem=16000

# tracking instance types
vm_instance_type=
vm_instance_cores=8
vm_instance_mem_gb=60
vm_location_code=

# cleanup
cleanupBams=true

# archive tarball
saveUploadArchive=true
uploadArchivePath=./seqware-results/upload_archive/

# options for tarball to SFTP
SFTPUploadArchive=false
# can be overwrite or skip, see https://trac.cyberduck.io/wiki/help/en/howto/cli
SFTPUploadArchiveMode=overwrite
SFTPUploadArchiveUsername=boconnor
SFTPUploadArchivePassword=klsdfskdjfskjd
SFTPUploadArchiveServer=10.1.1.13
SFTPUploadArchivePath=/upload/path/directory/

# options for tarball to S3
S3UploadArchive=false
S3UploadArchiveMode=overwrite
S3UploadArchiveBucketURL=s3://bucketname/uploads/
S3UploadArchiveKey=slkdfjslkdj
S3UploadArchiveSecretKey=lkdjflskdjflskdj

# send the files not a tarball
SFTPUploadFiles=false
# can be overwrite or skip, see https://trac.cyberduck.io/wiki/help/en/howto/cli
SFTPUploadMode=overwrite
SFTPUploadUsername=boconnor
SFTPUploadPassword=klsdfskdjfskjd
SFTPUploadServer=10.1.1.13
SFTPUploadPath=/upload/path/directory/

S3UploadFiles=false
S3UploadFileMode=overwrite
S3UploadBucketURL=s3://bucketname/uploads/
S3UploadKey=slkdfjslkdj
S3UploadSecretKey=lkdjflskdjflskdj

# synapse upload
SynapseUpload=false
SynapseUploadSFTPUsername=boconnor
SynapseUploadSFTPPassword=klsdfskdjfskjd
SynapseUploadUsername=boconnor
SynapseUploadPassword=klsdfskdjfskjd
SynapseUploadURL=sftp://tcgaftps.nci.nih.gov/tcgapancan/pancan/variant_calling_pilot_64/OICR_Sanger_Core
SynapseUploadParent=syn3155834

# if set, these trigger an upload of the input bam file to a GNOS repository
bamUploadServer=
bamUploadPemFile=
bamUploadStudyRefnameOverride=
bamUploadAnalysisCenterOverride=
bamUploadScriptJobMem=10000
bamUploadScriptJobSlots=1

# if set to true GNOS is still used for downloading metadata but the input bam file paths are assumed to be local file paths
# specifically tumourBams is a colon-delimited list of full file paths and controlBam is a full file path
localFileMode=
# if localFileMode is true then you need to give the path where the decider downloads all the XML
# this is the path that the VM/Docker/workflow sees (might be different from your path)
localXMLMetadataPath=

# another option for upload
skip-validate=false

# when localFileMode=true, if set this causes the bam file paths to be modified so they are <localBamFilePathPrefix>/<analysis_id>/<bam_file>, also affects the bai path implicitly. This is done so you can continue working with the decider.
localBamFilePathPrefix=

# END NEW ITEMS

# basic setup
coresAddressable=8
memHostMbAvailable=60000
tabixSrvUri=http://192.168.82.184/
pemFile=/mnt/home/seqware/gnos.pem
uploadPemFile=/mnt/home/seqware/gnos.pem
seqware-output-lines-number=8
gnosServer=https://gtrepo-dkfz.annailabs.com/
## comment out upload server to block vcfUpload
uploadServer=https://gtrepo-dkfz.annailabs.com

study-refname-override=icgc_pancancer_vcf
analysis-center-override=ebi
#center-override=
#ref-center-override=
upload-test=false
upload-skip=false

assembly=GRCh37
species=human
seqType=WGS
gender=L

# test data, will be overriden unless testMode=true
testMode=

# the donor information
tumourAliquotIds=7e10e325-16d2-42df-b957-df4d3a9477d0:280a069c-38e5-4300-a15c-2612301b70e3:2f79fe89-9d24-4fbe-ba5b-0ff6c3c4d663:1d6c9181-a02f-4c35-85b3-65dc5808f50e:2b54d668-7585-4bf4-9fdd-aea3c5cd4fa4:7d6fb1a7-7742-4b8c-9903-abff706240b5
tumourAnalysisIds=3850f675-e2d5-49b7-9c32-24ec2a20b97a:85d2c39c-0d74-40d4-bd26-ff5dd4067bc1:e1ec2227-a223-4469-a498-2e6241f4a349:79ee25e4-ab81-4420-82e0-a3db7b9d623c:727de6e2-db43-4b50-a06b-f1b65c55ef6c:701677cd-c3b7-45d5-a52e-7d6003bde95d
tumourBams=f9527c09de092778d44d4d9779bc9e29.bam:b1523b06f2d4be03c127e9670a8d1a96.bam:a6b5d0372f5ffbb7d615c1b99b8d514c.bam:4a3d67e6cd2913a7a0c01c7c89616359.bam:66aacd70a5728c11034700b3393d1576.bam:645d7cac7681bb83f73f9158853dc2dc.bam
controlAnalysisId=b3100edd-92bf-4d85-8d29-8284d0897e7d
controlBam=053d5013662f111e4abf59194329fc6a.bam

refExclude=MT,GL%,hs37d5,NC_007605`

**Comment by niall-byrne** [comment]
OK, after doing a replication of the issue I found that the warning messages themselves were just red herrings.  There is nothing wrong with the parameterization, the stdout was just deceiving in that the failure to parse the k parameter was indistinguishable from a hard failure.

I've done tests on 1.0.6 and 1.0.7.  
I'm closing this issue accordingly.
